package name.reidmiller.timeofemissions.model;

public enum Region {
	ALBERTA, ARKANSAS, LOUISIANA, MANITOBA, MICHIGAN, MINNESOTA, ILLINOIS, 
	INDIANA, IOWA, KANSAS, NEBRASKA, NORTH_DAKOTA, OKLAHOMA, ONTARIO, 
	SOUTH_DAKOTA, WISCONSIN;
}
